### ISSUE TITLE
Next and Previous image are misplaced when used in SproutCore application

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cbeyls/slimbox#26]
```
What steps will reproduce the problem?
1. Create SproutCore application.
2. Invoke slimbox with multiple images
3. Hover with the mouse on both sides of the image

What is the expected output? What do you see instead?
Next show when mouse is at the right half of the photo and Previous on the left 
side.

What version of the product are you using? On what operating system?
Slimbox v2.04


```

Original issue reported on code.google.com by `ido....@gmail.com` on 12 Nov 2010 at 4:11

**Comment by cbeyls** [comment]
Your issue does not describe how exactly are the previous and next images misplaced. Are they inverted? If they are, you may be using the right-to-left CSS file instead of the regular one. If you're not, this may be a conflict with the CSS code of SproutCore, but I doubt it.
