### ISSUE TITLE
The image is much larger than browser window size

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cbeyls/slimbox#28]
```
I would like to show image but make sure it is never bigger then the available 
client area.
If the image is bigger then I would like it to be as big as possible but never 
bigger than what the client can see.
```

Original issue reported on code.google.com by `ido....@gmail.com` on 18 Nov 2010 at 11:29

**Comment by cbeyls** [comment]
Slimbox does not auto-resize images but a few other libraries can.
This is mainly due to the fact that it displays the image using the background-image CSS property and you can not resize an image with this technique.
