### ISSUE TITLE
Only 4 Images Per Page

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cbeyls/slimbox#30]
```
Only 4 images shows up per page, the total gallery has about 90 images in it - 
how can I modify this so that I can browse all at once?
Now I have to go through about 26 pages with 4 images on each...
Can't figure how to change this
Please help

This is in Google Chrome on Wordpress 3 on a Laptop with Windows XP I think
```

Original issue reported on code.google.com by `j.oeverg...@gmail.com` on 16 Mar 2011 at 3:36

Attachments:
* [Untitled-1.jpg](https://storage.googleapis.com/google-code-attachments/slimbox/issue-30/comment-0/Untitled-1.jpg)

**Comment by cbeyls** [comment]
You can use the API to launch a custom big gallery from a single link or button. Please read the docs.
Otherwise, you can just put 90 image links with the same "rel" attribute value in your page.
