### ISSUE TITLE
Missing $ at ln 6 col 170

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cbeyls/slimbox#33]
```
What steps will reproduce the problem?
1. Download 1.8 released 20 aug
2. Install, wont work
3. check javascript error log:
>Uncaught exception: TypeError: '$(document.body).adopt' is not a function

I added an $ and then it worked. Thats all i know im not a Mootools developer, 
i dont know this stuff.
```

Original issue reported on code.google.com by `koliba...@gmail.com` on 11 Nov 2011 at 11:59

**Comment by cbeyls** [comment]
This looks like a conflict between MooTools and another Javascript library using the $ symbol, like jQuery. Try to use only one of those libraries or use the special "no conflict" mode of MooTools.
