### ISSUE TITLE
Reversed sort order when div holding images is float:right.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cbeyls/slimbox#34]
```
What steps will reproduce the problem?
1. put im,ages in div
2. let that div float right
3. the first picture is now the last picture according to slimbox

What is the expected output? What do you see instead?
the most left picture being number 1 on the image list.

What version of the product are you using? On what operating system?
v1.71



```

Original issue reported on code.google.com by `thapri...@gmail.com` on 9 Dec 2011 at 11:55

**Comment by cbeyls** [comment]
It's not a bug; Slimbox by default uses the order the image links appear in the HTML code, not the order you see them displayed on the screen with custom CSS rules.
If you want to display images in a custom order, please use the API to specify the images list manually, in the order you want.
