### ISSUE TITLE
Rescan?

### ISSUE THREAD

**Issue by cheesegrits** [cbeyls/slimbox#44]
There doesn't seem to be a way to rescan any more?  The original versions has Slimbox.scanPage, which I could trigger when (say) updating the DOM through AJAX.

**Comment by cbeyls** [comment]
You can find the default scan code in autoload.js:

```
$("a[rel^='lightbox']").slimbox({/* Put custom options here */}, null, function(el) {
	return (this == el) || ((this.rel.length > 8) && (this.rel == el.rel));
});
```
The idea is that you can change this code to suit your needs.
